# Generated by Django 4.2.2 on 2024-02-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('background', models.CharField(max_length=50)),
                ('fontfamily', models.CharField(max_length=50)),
            ],
        ),
    ]
